In [31]:
import torch
import torchvision

In [38]:
x = torch.empty(3,5, dtype=torch.float32)

In [39]:
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [40]:
x[0][0]

tensor(0.)

In [41]:
y = x.new_ones(3,3)

In [42]:
y.dtype

torch.float32

In [43]:
torch.randn_like(x)

tensor([[-0.3086, -0.9365,  0.3400,  0.4870, -0.1010],
        [ 0.3302,  0.1674,  1.4120, -2.1623,  0.1959],
        [-0.1822, -0.4022, -0.8435, -1.0524,  0.6863]])

In [44]:
torch.cuda.is_available()

True

In [49]:
y = torch.rand(3,5)
z = torch.rand(3,5)

In [50]:
y + z

tensor([[1.4214, 0.4630, 0.9486, 1.4953, 0.6556],
        [1.4252, 1.1255, 1.5252, 0.9479, 1.3681],
        [0.8009, 1.0838, 0.8989, 0.9747, 1.2044]])

In [51]:
torch.add(y, z)

tensor([[1.4214, 0.4630, 0.9486, 1.4953, 0.6556],
        [1.4252, 1.1255, 1.5252, 0.9479, 1.3681],
        [0.8009, 1.0838, 0.8989, 0.9747, 1.2044]])

In [55]:
result = torch.zeros(3,5)
torch.add(y, z, out=result)

tensor([[1.4214, 0.4630, 0.9486, 1.4953, 0.6556],
        [1.4252, 1.1255, 1.5252, 0.9479, 1.3681],
        [0.8009, 1.0838, 0.8989, 0.9747, 1.2044]])

In [57]:
y.sub_(x)

tensor([[0.6486, 0.1080, 0.4125, 0.5799, 0.1934],
        [0.5345, 0.2709, 0.6880, 0.1718, 0.5300],
        [0.4605, 0.8256, 0.2481, 0.5983, 0.6615]])

In [58]:
y

tensor([[0.6486, 0.1080, 0.4125, 0.5799, 0.1934],
        [0.5345, 0.2709, 0.6880, 0.1718, 0.5300],
        [0.4605, 0.8256, 0.2481, 0.5983, 0.6615]])

## Working with numpy

In [45]:
import numpy as np

In [47]:
a = np.random.rand(3,5)

In [59]:
a_tensor = torch.from_numpy(a)

In [63]:
a_tensor.device

device(type='cpu')

In [64]:
a

array([[0.49154423, 0.66010896, 0.43097429, 0.79472158, 0.29419111],
       [0.68580059, 0.0920146 , 0.97996571, 0.15766495, 0.68306533],
       [0.43728841, 0.79046656, 0.79626913, 0.79703388, 0.26361772]])

In [65]:
a[0][0] = 2.33

In [66]:
a_tensor

tensor([[2.3300, 0.6601, 0.4310, 0.7947, 0.2942],
        [0.6858, 0.0920, 0.9800, 0.1577, 0.6831],
        [0.4373, 0.7905, 0.7963, 0.7970, 0.2636]], dtype=torch.float64)

In [67]:
x.numpy()

array([[0.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e-45],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00]], dtype=float32)

## CUDA device

In [68]:
torch.cuda.is_available()

True

In [69]:
device = torch.device('cuda')

In [70]:
device

device(type='cuda')

In [71]:
a_tensor.to(device)

tensor([[2.3300, 0.6601, 0.4310, 0.7947, 0.2942],
        [0.6858, 0.0920, 0.9800, 0.1577, 0.6831],
        [0.4373, 0.7905, 0.7963, 0.7970, 0.2636]], device='cuda:0',
       dtype=torch.float64)

In [72]:
a_tensor.device

device(type='cpu')