In [1]:
import torch

In [4]:
x = torch.ones(3,3, requires_grad=True)

In [5]:
y = (x * 3).mean()

In [6]:
y

tensor(3., grad_fn=<MeanBackward0>)

y.grad_fn stores the history of how this tensor was created, this info is used to backprop and find the gradient of other variables

In [8]:
y.grad_fn

backward() perfroms the backprop and stores the respective gradient on each variables, `grad` attribute

In [11]:
y.backward()

In [12]:
print(x.grad)

tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])


explanation

$y = 1/3 \sum_{i=1}^3 x_i * 3$

On differentiation

$\partial y/\partial x = x/3$

The above one was simple because the output was scalar, if the output was a vector, a vector has to passed to `backward`, which is mulltipled with the jacobian.

In [64]:
a = torch.ones(3,3, requires_grad=True)
b = (a * a) / 4

On calling backward once the grad_fn is flushed out, to retain it pass `retain_graph`

In [65]:
b.backward(torch.ones(3, 3), retain_graph=True)

In [66]:
a.grad

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

In [67]:
b

tensor([[0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500]], grad_fn=<DivBackward0>)

In [68]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [69]:
b.backward(torch.zeros(3, 3) + 4, retain_graph=True)

In [70]:
a.grad

tensor([[2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000]])

In [71]:
torch.ones(3, 3) + 4

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [72]:
b.backward(torch.zeros(3, 3) + 10, retain_graph=True)

In [73]:
a.grad

tensor([[7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000]])

In [55]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

From the above outputs, it's clear that `a.grad` keeps adding up values everytime a backprop is done 0.5 + 2 + 5 = 7.5

In [74]:
print(a.requires_grad)
print((a ** 2).requires_grad)

with torch.no_grad():
    print((a ** 2).requires_grad)

True
True
False
